apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 4
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: topaztechnology/redis:4.0.2
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_TYPE
          value: server
        volumeMounts:
        - name: redis-data
          mountPath: /redis/data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      annotations:
        volume.beta.kubernetes.io/storage-class: vsphere
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
